//
//  PostModels.swift
//  FirstExampleCleanSwift
//
//  Created by ely.assumpcao.ndiaye on 01/06/19.
//  Copyright (c) 2019 ely.assumpcao.ndiaye. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PostScene {
    // MARK: Use cases
    
    enum Load {
        struct Request
        {
        }
        struct Response
        {
            let posts: [Post]
        }
        struct ViewModel
        {
            let posts: [Post]
        }
    }
    
    enum Comments {
        //O Request vai passar o post que acabou de ser tocado
        struct Request {
            let post: Post
        }
        struct Response
        {
            
        }
        struct ViewModel
        {
            
        }
    }
    
}
