//
//  PostWorker.swift
//  FirstExampleCleanSwift
//
//  Created by ely.assumpcao.ndiaye on 01/06/19.
//  Copyright (c) 2019 ely.assumpcao.ndiaye. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class PostWorker {
    func fetchPosts(completionHandler: @escaping ([Post]) -> Void) {
        print("Passou no worker")
        NetworkManager.shared.getPosts { posts in
            completionHandler(posts)
        }
    }
    
}
