//
//  PostRouter.swift
//  FirstExampleCleanSwift
//
//  Created by ely.assumpcao.ndiaye on 01/06/19.
//  Copyright (c) 2019 ely.assumpcao.ndiaye. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PostRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    //Obs quando tiver storyboard necessita passar como parametro como o exemplo acima^
    func routeToComments()
}

protocol PostDataPassing {
    var dataStore: PostDataStore? { get }
}

class PostRouter: NSObject, PostRoutingLogic, PostDataPassing
{
    weak var viewController: PostViewController?
    var dataStore: PostDataStore?
    
    // MARK: Routing
    func routeToComments(){
        //Var que recebe a View de destino a ser mudada
        let destinationVC = CommentViewController()
        // Var que recebe dados (postId) provenientes da PosT
        var destinationDS = destinationVC.router!.dataStore!
        //Passando Dados
        passDataToComments(source: dataStore!, destination: &destinationDS)
        // CHamada DA Navegacao das telas
        navigateToComments(source: viewController!, destination: destinationVC)
        
    }
    
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    //{
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}
    
    // MARK: Navigation
    //Funcao para navegacao
    func navigateToComments(source: PostViewController, destination: CommentViewController) {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    //funcao para transicao de dados
    func passDataToComments(source: PostDataStore, destination: inout CommentDataStore) {
        destination.postId = source.postId
    }
}
