//
//  PostPresenter.swift
//  FirstExampleCleanSwift
//
//  Created by ely.assumpcao.ndiaye on 01/06/19.
//  Copyright (c) 2019 ely.assumpcao.ndiaye. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PostPresentationLogic {
    func presentSomething(response: PostScene.Load.Response)
    //Chamada
    func presentComments(response: PostScene.Comments.Response)
}

class PostPresenter: PostPresentationLogic {
    weak var viewController: PostDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: PostScene.Load.Response) {
        // Cria um viewmodel que ira passar algo pra view controller atraves da funcao displaySomething
        let viewModel = PostScene.Load.ViewModel(posts: response.posts)
        viewController?.displaySomething(viewModel: viewModel)
    }
    
    func presentComments(response: PostScene.Comments.Response) {
        let viewModel = PostScene.Comments.ViewModel()
        //Chamamos a funcao que esta na PostViewController informando por parametro para qual view queremos migrar(route)
        viewController?.displayComments(viewModel: viewModel)
    }
}
