//
//  CommentModels.swift
//  FirstExampleCleanSwift
//
//  Created by ely.assumpcao.ndiaye on 04/06/19.
//  Copyright (c) 2019 ely.assumpcao.ndiaye. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CommentScene
{
  // MARK: Use cases
  
  enum Load
  {
    struct Request
    {
    }
    struct Response
    {   //variavel para configurar a resposta espera para usarmos no interactor (response)
        let comments: [Comment]
    }
    struct ViewModel
    {
        let comments: [Comment]
    }
  }
}
