//
//  CommentWorker.swift
//  FirstExampleCleanSwift
//
//  Created by ely.assumpcao.ndiaye on 04/06/19.
//  Copyright (c) 2019 ely.assumpcao.ndiaye. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CommentWorker
{
    func fetchComments(postId: Int, completionHandler: @escaping ([Comment]) -> Void) {
        print("Passou no workerComment")
        NetworkManager.shared.getCommentsForPost(withPostId: "\(postId)") { (comments) in
            completionHandler(comments)
        }
    }
}
