//
//  CommentInteractor.swift
//  FirstExampleCleanSwift
//
//  Created by ely.assumpcao.ndiaye on 04/06/19.
//  Copyright (c) 2019 ely.assumpcao.ndiaye. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CommentBusinessLogic
{
    func doLoadInitialData(request: CommentScene.Load.Request)
}

protocol CommentDataStore
{
    var postId: Int { get set }
}

class CommentInteractor: CommentBusinessLogic, CommentDataStore{
    var presenter: CommentPresentationLogic?
    var worker: CommentWorker?
    //Implementar o procolo CommentDataStore
    var postId: Int = 0
    
    // MARK: Do something
    
    func doLoadInitialData(request: CommentScene.Load.Request)
    {
        worker = CommentWorker()
        //O interactor tem o valor do postId pq ele puxa do DataStore
        worker?.fetchComments(postId: postId, completionHandler: { (comments) in
            let response = CommentScene.Load.Response(comments: comments)
            self.presenter?.presentInitialData(response: response)
        })
    }
}
